### ISSUE TITLE
PLay 128x32 animated GIF

### ISSUE THREAD

**Issue by pinballsp** [pixelmatix/AnimatedGIFs#14]
Hello.

I need play videos with 128x32 resolution. I have do the animated GIF, but when I config kMatrixWidth with 128 and run, screen show message "No gifs directory".

With same SD card, same files, if I coinfig kMatrixWidth with 32 or 64, then play video but only 32x32,  4 times in screen and only part of the animation screen of the animated GIF.

So, how may I config software to play 128x32 animated GIF videos ?.
My led panels are two P2.5, 64x32 piexel, Scan 1/16 chained.

Thank you and kind regards.

**Comment by embedded-creations** [comment]
It could be from having not enough RAM to run the SD library.  Did you follow the instructions for a 128x32 display listed in the sketch?

 *  - Note for 128x32 and 64x64 displays - need to reduce RAM:
 *    set kRefreshDepth=24 and kDmaBufferRows=2 or set USB Type: "None" in Arduino,
 *    decrease refreshRate in setup() to 90 or lower to get good an accurate GIF frame rate
 *  - WIDTH and HEIGHT are defined in GIFParseFunctions.cpp, update to match the size of your GIFs
 *    only play GIFs that are size WIDTHxHEIGHT or smaller

**Comment by pinballsp** [comment]
Hello Louis.

Thanks, now work, I did not see that must modify also the WIDTH in GIFParseFunctions.cpp. I modified all about reduce RAM memory, at any rate I'm testing it with a Teensy 3.6, so suppose no problem with RAM size.

thank you and kind regards.

**Comment by embedded-creations** [comment]
Great, glad you got it working.  Having to change width in two places is a pain and easy to overlook, it's on my list to improve in the future.

**Comment by pinballsp** [comment]
Thanks, one more question please.
Can not adjust the general brightness level ??, I have modify defaultBrightness value (0-255), but brightness level keep always high.

I have another application with Smartmatrix and I may modify brightness level with matrix.setBrightness(x); // where x is 0-255

**Comment by embedded-creations** [comment]
You should be able to change `defaultBrightness` in the sketch and that will work:

https://github.com/pixelmatix/AnimatedGIFs/blob/master/AnimatedGIFs.ino#L82

**Comment by pinballsp** [comment]
Yes, I changed but no results, brightness level keep same always.
I will check to see if the Output Enable pin is not connected or connected to another pin.
