### ISSUE TITLE
librarification

### ISSUE THREAD

**Issue by ladyada** [pixelmatix/AnimatedGIFs#27]
heya louis, could this code be split into a library so it can be more easily used for other types of displays (i have a version for TFT)

**Comment by embedded-creations** [comment]
Yep, that's something I've been wanting to do for a while.

Marc Merlin has been doing a lot on his AnimatedGIFs fork, and announced this recently, but I haven't tried it myself:

https://community.pixelmatix.com/t/announce-animatedgifs-fork-now-usable-as-a-library/392

**Comment by ladyada** [comment]
thanks! it looks like a great start-
i like the idea of separating display, decode and filesys logic completely - sorta like this person did https://github.com/prenticedavid/AnimatedGIFs_SD/blob/master/AnimatedGIFs_SD.ino
ill use that for now :)

**Comment by embedded-creations** [comment]
Also, see this PR: https://github.com/pixelmatix/AnimatedGIFs/pull/11

**Comment by embedded-creations** [comment]
See https://github.com/pixelmatix/GifDecoder which is now a wrapper around the efficient GIF decoder library https://github.com/bitbank2/AnimatedGIF
