### ISSUE TITLE
Sections of the GIF are disappearing

### ISSUE THREAD

**Issue by Bryce-Toma** [pixelmatix/AnimatedGIFs#32]
I made a few hand-made gifs for the display and one of the four does not display properly. I am able to display 60+ gifs that I found online. The only one that is giving me problems is a GIF I hand-made. I am experiencing some "clipping" of the gif, where sections of it do **not** display. It only updates certain rows and/or columns of moving animations/LEDs.  The portions of LEDs don't turn on when "FINALS" and "JOB REJECTION" and "MEMES" show up. 

To try and fix it: 
1a)	Removed the red overlay (over-processing?) -> still failed. Still certain segments did not display
1b)   Removed the closing and opening of the mouth aniation. Mouth just close -> still failed. "
2)	Tried lowering the refresh rate in Arduino code (default Refresh rate is 90) 
-  First to 70 -> no change in the clipping
- Tried 20 -> still clipped and seizure-inducing flashing
3)	Reduced the frame rate of the GIF. (100ms to 75ms) -> slower gifs, and still clipped.
4)	Added more frames in the animation. (From around 60 frames to 140 frames) -> slightly better and smoother animation but still clipping and blackouts.

All the above solutions that I tried did not fix the issue. It's not a hardware issue because I am able to display a full 1024 LED output. I believe it lies within the clearing function of the software. 

See the following file for the aforementioned problem GIF:
![BryMan](https://user-images.githubusercontent.com/8802347/55448082-03db5900-558c-11e9-972e-84f00f601199.gif)

**Comment by embedded-creations** [comment]
There’s probably some bugs in the library that need to get tracked down and fixed, but in the meantime to try and get your gif working, go to Ezgif.com and run it through something that doesn’t significantly change the Gif but reencodes it

**Comment by Mad182** [comment]
The GIF is optimized for smaller file size by making some unchanged sections of consecutive frames transparent.

You can see this if you split the GIF to frames without redrawing them.

![split](https://user-images.githubusercontent.com/798148/55483511-65083880-562f-11e9-9add-a1d3b259cf77.png)

You can use https://ezgif.com/optimize with optimization method _Coalesce (unoptimize)_ as a workaround.

**Comment by Bryce-Toma** [comment]
@Mad182 and @embedded-creations,
Thanks guys for your prompt replies! Those are some great ideas! Since I made the GIF in a separate program, I didn't even consider running it through ezgif.com. It's strange that the program that I was using optimized it though to make the file smaller by removing unchanged animations. Thank you, I didn't know "coalesce" was a workaround. And your solution fixed my problem! :D

**Comment by Bryce-Toma** [comment]
I ran the GIF through ezgif.com and applied "coalesce" as suggested by Mad182, and it did fix the portions of the frames that were not previously displaying. However, now some colors are being inverted. 

Blue -> Yellow. Yellow -> Blue. Orange -> Green, etc. 

Attached is a link to a video of what I'm experiencing. 
https://drive.google.com/file/d/12rJEzxaQoCuA9VdgSyawxCRWsy70d3le/view?usp=sharing

**Comment by embedded-creations** [comment]
Try some other modes, not necessarily coalesce.  I've noticed that not all modes in ezgif work properly with the AnimatedGIFs sketch.

Do the inverted colors show up when viewing the GIF on your computer?

**Comment by Bryce-Toma** [comment]
I'll do some experimenting! Thanks, for your observation and suggestion! 
No, the inverted colors do not show up when viewing the GIF on my computer. 
By running the GIF through the splitter via exgif.com, I wasn't able to locate the color inversion either. 
![splitter_ezgiff](https://user-images.githubusercontent.com/8802347/55488974-adefcb00-55f6-11e9-9d83-6d6b75426663.png)

**Comment by Bryce-Toma** [comment]
I was able to fix the issues, by applying two optimizations to the GIF:
1) coalesce (to unoptimize the image and fix portion display)
2) single color table (fix color inversion)
The GIF now runs perfectly! Thank you, both, for your help! :)
