### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by tarbear123** [pixelmatix/AnimatedGIFs#33]
what do these lines mean?

```
File directory = SD.open(directoryName);
    if (!directory)
        return;
   
 File file = directory.openNextFile();
    while (file && (index >= 0)) {
        filename = (char*)file.name();

        if (isAnimationFile(file.name())) {
            index--;
```

and why is this false?
num_files = enumerateGIFFiles(GIF_DIRECTORY, false);

**Comment by embedded-creations** [comment]
Hi, you can ask questions in our community linked below, this area is for issues with the code

community.pixelmatix.com

> and why is this false?
> num_files = enumerateGIFFiles(GIF_DIRECTORY, false);

It's passing false to that function to tell it not to print the filenames for debugging
