### ISSUE TITLE
Wrong Colors for all gifs

### ISSUE THREAD

**Issue by mcaustin2019** [pixelmatix/AnimatedGIFs#34]
When I load the sketch, all gifs(mine and the examples) seem to be playing with incorrect colors(blues are yellows, etc.).  What could be causing this?

**Comment by mcaustin2019** [comment]
i figured it out.

i changed the following and the colors look correct now.

void drawPixelCallback(int16_t x, int16_t y, uint8_t blue, uint8_t green, uint8_t red) {
  backgroundLayer.drawPixel(x, y, {red, green, blue});

**Comment by embedded-creations** [comment]
Is your matrix working normally and displaying colors correctly with another sketch?

**Comment by embedded-creations** [comment]
Please post to community.pixelmatix.com if you need more help
