### ISSUE TITLE
Gif only playing first 10 sec.

### ISSUE THREAD

**Issue by Rosheger** [pixelmatix/AnimatedGIFs#37]
Hi!

I made a gif that has no trouble playing/looks great...for about 10 sec (first 100 frames or so of 200 frames) then it cuts off and loops to the beginning. When I play the gif on the computer it plays the full loop no problem. 

I saw the discussion here https://github.com/pixelmatix/AnimatedGIFs/issues/32 and followed the workaround that was successful in that case but made no difference for me.

Any suggestions would be very  appreciated!

**Comment by Rosheger** [comment]
![ledfull01_16opti](https://user-images.githubusercontent.com/25311349/59126039-0c586300-8932-11e9-9e93-9cd50822f21a.gif)

**Comment by Rosheger** [comment]
Wow I feel dumb..jumped the gun and posted before looking into the code. 

In case anyone overlooks this, the default line in the script is:

#define DISPLAY_TIME_SECONDS 10

which once changed to longer resolved the clipping.

**Comment by embedded-creations** [comment]
I'm pretty sure I've done the same thing.

I'm going to add some comments to the code to "(make sure this is longer than your GIF!)", and a new issue to improve this behavior: https://github.com/pixelmatix/AnimatedGIFs/issues/38
