### ISSUE TITLE
GIF discoloration near maximum brightness

### ISSUE THREAD

**Issue by rorosaurus** [pixelmatix/AnimatedGIFs#40]
Perhaps this is an artifact of scanning displays in general, but it seems unexpected to me.

At brightness below ~200/255, I see colors reflected accurately in the output.
At brightness above ~200/255, I see color artifacts in the output.

It appears to be focused on edges where light and dark colors meet.  Light tan and brown edges become purple, cyan, and sometimes red.

Sorry for this terrible GIF, it's hard to capture the output on these scanning displays. :)

![Example](https://thumbs.gfycat.com/AdeptEnviousFox-size_restricted.gif)
Higher resolution: https://gfycat.com/adeptenviousfox

**Comment by embedded-creations** [comment]
Could be related to the LEDs drawing more power than is available.  Try using a bigger power supply.  Try only turning half the pixels on (e.g. blank the right half), and see if the artifacts go away.
