### ISSUE TITLE
Gif Decoding

### ISSUE THREAD

**Issue by philspitlerSF** [pixelmatix/AnimatedGIFs#43]
I cannot get the attached gif to play on my smartmatrix v4 using a Teensy 3.6

In the serial monitor the sketch does report the file name.

![omar02](https://user-images.githubusercontent.com/15186070/81771518-11a22400-9498-11ea-8d33-19e8363781b3.gif)

**Comment by embedded-creations** [comment]
Try reencoding the GIF with ezgif.com, it may have a mode that isn't supported
