### ISSUE TITLE
GIF only plays in red

### ISSUE THREAD

**Issue by appleseed13** [pixelmatix/AnimatedGIFs#6]
I am able to load and play gifs on the matrix but they only appear in red. I have tried several different gifs  and used gifs containing many different colors but still only red shows on the matrix.

![toad](https://cloud.githubusercontent.com/assets/15489550/10860781/020f9068-7f44-11e5-86e1-1d85d5bcfbb0.gif)

**Comment by embedded-creations** [comment]
have you tried any other sketches?  Do they show red, green, blue or just red? A quick test: remove the SD card, what color is the error message?

**Comment by appleseed13** [comment]
I just ran a fastLED sketch and the other colors were present. Also, the error message appears in yellow. A bit better description of what is happening, the GIF above is a solid red mass that rotates.  I also have tried a white buffering wheel and the matrix gets the brightness right but the wheel appears in red instead of white. Aside from the color it works perfectly.

**Comment by embedded-creations** [comment]
Very strange, never heard of this problem before.  Can you run the bitmaps example, and compare what you see to the original color wheel and Pixelmatix logo?
https://github.com/pixelmatix/SmartMatrix/tree/master/examples/Bitmaps/SourceBitmaps

What power supply are you using?

**Comment by appleseed13** [comment]
I am using a 5 volt, 4 amp supply.  The bitmaps example ran with mixed results. The google image appeared as it should but the color wheel was only in red, bright where red should be and fades to black on the other half of the circle.  As for the Pixelmatix logo, the whole matrix lit up in red.

**Comment by embedded-creations** [comment]
Seems like you're not getting enough power to the panel.  There's enough power leaking through the data lines to power up the red LEDs, but not enough to power blue or green.  Check your power cables, and use a meter to check power at the panel, make sure it's getting 5V.

**Comment by appleseed13** [comment]
It was a power issue.  Got it working with a full range of colors now. Thanks for the help!!

**Comment by embedded-creations** [comment]
You're welcome!
