### ISSUE TITLE
64x64 animated gif

### ISSUE THREAD

**Issue by Dan7766** [pixelmatix/AnimatedGIFs#9]
All the documentation points to 32x32 gifs but i have a 64x64 panel on its way and was wondering if 64x64 gifs are supported ?, would be a shame to not fill the panel fully when playing back a gif..

Thanks

**Comment by Dan7766** [comment]
sorry delete this, my panel arrived early and i tried a 64x64 and all works. Should have been more patient works well at full screen just a little slow but think thats the settings.

**Comment by embedded-creations** [comment]
No problem Dan, glad it's working!  You can tweak the settings a bit, see the top of the AnimatedGIFs file which has comments, but I agree, it's a little slow and a little bit of a slow refresh rate at 64x64 as this is pushing the limits of the Teensy

**Comment by Dan7766** [comment]
Thanks for the reply, appreciate it..

One thing i am having an issue with is changing the brightness. No matter
what i set it to its always full brightness..
Can you think of what i might be doing wrong?

Thanks again
Daniel

**Comment by embedded-creations** [comment]
not sure, can you paste the full code to your sketch here (or on a github gist) so I can look for the issue?

**Comment by Dan7766** [comment]
The code is just the straight animated gif code example, the only changes
ive made are for the resolution of the panel 64 x 64 and the suggested
changes for speed that are listed in the code.

* set kRefreshDepth=24 and kDmaBufferRows=2


This is the line for brightness ? or is there other areas that im
overlooking?

// range 0-255
const int defaultBrightness = 255;

**Comment by embedded-creations** [comment]
Ah, there's no code that actually uses `defaultBrightness`.  Add this line to setup():

`  matrix.setBrightness(defaultBrightness);`

**Comment by embedded-creations** [comment]
I'll get that fixed with the next release

**Comment by Dan7766** [comment]
Thanks, guess i should have known that.. Still learning im afraid..

Thanks again for the help
